<a href="https://colab.research.google.com/github/syamsulrizal123/SLO/blob/main/Simple_ANN_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def sigmoid_derivative(x):
  return x * (1 - x)

In [ ]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [ ]:
training_outputs = np.array([[0,1,1,0]]).T
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3, 1)) -1
synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [ ]:
for iteration in range(1):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))
print('outpus after training: ')
print(outputs)

In [ ]:
for iteration in range(20000):
  #Forward Propagation
  input_layer = training_inputs
  outputs=sigmoid(np.dot(input_layer, synaptic_weights))

  error = training_outputs - outputs
  
  #Backpropagation
  adjustments = error * sigmoid_derivative(outputs)

  synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic Weights after training')
print(synaptic_weights)

print('Output after training')
print(outputs)


Synaptic Weights after training
[[11.49345763]
 [-0.2048909 ]
 [-5.54227641]]
Output after training
[[0.00390234]
 [0.99681554]
 [0.99740397]
 [0.00318168]]


In [ ]:
for j in outputs:
  print(np.around(j))

[0.]
[1.]
[1.]
[0.]
